/**
 * directTransfer — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface GeneratePaymentAmountBody {
  order: {
      /** TODO: verify against developers.doku.com */
    amount?: number;
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
      /** TODO: verify against developers.doku.com */
    item_name?: string;
      /** TODO: verify against developers.doku.com */
    customer_address?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
  };
}

/** Generate Payment Amount — POST /bca-direct-transfer/v1/order */
export async function generatePaymentAmount(
  client: DokuClient, body: GeneratePaymentAmountBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/bca-direct-transfer/v1/order", body as unknown as Record<string, unknown>);
}
