/**
 * directDebitSnap — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface DirectDebitSnapSnapOptions {
  /** CHANNEL-ID header (some flows require e.g. "H2H") */
  channelId?: string;
  /** B2B2C customer token; sent as `Authorization-Customer: Bearer ...` when set */
  customerToken?: string;
}

export interface OvoAccountBindingBody {
    /** TODO: verify against developers.doku.com */
  phoneNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    custIdMerchant?: string;
      /** TODO: verify against developers.doku.com */
    customerName?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    idCard?: string;
      /** TODO: verify against developers.doku.com */
    country?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    dateOfBirth?: string;
      /** TODO: verify against developers.doku.com */
    successRegistrationUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedRegistrationUrl?: string;
  };
}

/** Account Binding — POST /direct-debit/core/v1/registration-account-binding */
export async function ovoAccountBinding(
  client: DokuClient, body: OvoAccountBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-account-binding", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface OvoBalanceInquiryBody {
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Balance Inquiry — POST /direct-debit/core/v1/balance-inquiry */
export async function ovoBalanceInquiry(
  client: DokuClient, body: OvoBalanceInquiryBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/balance-inquiry", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface OvoPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  feeType?: string;
    /** TODO: verify against developers.doku.com */
  payOptionDetails?: Array<unknown>;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    successPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    paymentType?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function ovoPayment(
  client: DokuClient, body: OvoPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface OvoRefundBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
    /** TODO: verify against developers.doku.com */
  reason?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function ovoRefund(
  client: DokuClient, body: OvoRefundBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface OvoAccountUnbindingBody {
    /** TODO: verify against developers.doku.com */
  tokenId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Account Unbinding — POST /direct-debit/core/v1/registration-account-unbinding */
export async function ovoAccountUnbinding(
  client: DokuClient, body: OvoAccountUnbindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-account-unbinding", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface CimbAccountBindingBody {
    /** TODO: verify against developers.doku.com */
  phoneNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    custIdMerchant?: string;
      /** TODO: verify against developers.doku.com */
    customerName?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    idCard?: string;
      /** TODO: verify against developers.doku.com */
    country?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    dateOfBirth?: string;
      /** TODO: verify against developers.doku.com */
    successRegistrationUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedRegistrationUrl?: string;
  };
}

/** Account Binding — POST /direct-debit/core/v1/registration-account-binding */
export async function cimbAccountBinding(
  client: DokuClient, body: CimbAccountBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-account-binding", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface CimbPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    remarks?: string;
      /** TODO: verify against developers.doku.com */
    successPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedPaymentUrl?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function cimbPayment(
  client: DokuClient, body: CimbPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface CimbVerifyOtpPaymentBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  otp?: string;
    /** TODO: verify against developers.doku.com */
  action?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    bankCardToken?: string;
  };
}

/** Verify OTP Payment — POST /direct-debit/core/v1/otp-verification */
export async function cimbVerifyOtpPayment(
  client: DokuClient, body: CimbVerifyOtpPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp-verification", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface CimbRefundBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
    /** TODO: verify against developers.doku.com */
  reason?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function cimbRefund(
  client: DokuClient, body: CimbRefundBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface CimbAccountUnbindingBody {
    /** TODO: verify against developers.doku.com */
  tokenId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Account Unbinding — POST /direct-debit/core/v1/registration-account-unbinding */
export async function cimbAccountUnbinding(
  client: DokuClient, body: CimbAccountUnbindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-account-unbinding", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface CimbVerifyOtpUnbindingBody {
    /** TODO: verify against developers.doku.com */
  otp?: string;
    /** TODO: verify against developers.doku.com */
  action?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    bankCardToken?: string;
  };
}

/** Verify OTP Unbinding — POST /direct-debit/core/v1/otp-verification */
export async function cimbVerifyOtpUnbinding(
  client: DokuClient, body: CimbVerifyOtpUnbindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp-verification", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface AlloAccountBindingBody {
    /** TODO: verify against developers.doku.com */
  phoneNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    custIdMerchant?: string;
      /** TODO: verify against developers.doku.com */
    customerName?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    idCard?: string;
      /** TODO: verify against developers.doku.com */
    country?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    dateOfBirth?: string;
      /** TODO: verify against developers.doku.com */
    successRegistrationUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedRegistrationUrl?: string;
      /** TODO: verify against developers.doku.com */
    deviceModel?: string;
      /** TODO: verify against developers.doku.com */
    osType?: string;
      /** TODO: verify against developers.doku.com */
    channelId?: string;
  };
}

/** Account Binding — POST /direct-debit/core/v1/registration-account-binding */
export async function alloAccountBinding(
  client: DokuClient, body: AlloAccountBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-account-binding", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface AlloBalanceInquiryBody {
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Balance Inquiry — POST /direct-debit/core/v1/balance-inquiry */
export async function alloBalanceInquiry(
  client: DokuClient, body: AlloBalanceInquiryBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/balance-inquiry", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface AlloPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  payOptionDetails?: Array<unknown>;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    successPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedPaymentUrl?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function alloPayment(
  client: DokuClient, body: AlloPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface AlloRefundBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
    /** TODO: verify against developers.doku.com */
  reason?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function alloRefund(
  client: DokuClient, body: AlloRefundBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface AlloAccountUnbindingBody {
    /** TODO: verify against developers.doku.com */
  tokenId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Account Unbinding — POST /direct-debit/core/v1/registration-account-unbinding */
export async function alloAccountUnbinding(
  client: DokuClient, body: AlloAccountUnbindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-account-unbinding", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface BriCardBindingBody {
    /** TODO: verify against developers.doku.com */
  cardData?: string;
    /** TODO: verify against developers.doku.com */
  custIdMerchant?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
    /** TODO: verify against developers.doku.com */
  phoneNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    customerName?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    idCard?: string;
      /** TODO: verify against developers.doku.com */
    country?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    dateOfBirth?: string;
      /** TODO: verify against developers.doku.com */
    successRegistrationUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedRegistrationUrl?: string;
  };
}

/** Card Binding — POST /direct-debit/core/v1/registration-card-bind */
export async function briCardBinding(
  client: DokuClient, body: BriCardBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-card-bind", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface BriVerifyOtpBindingBody {
    /** TODO: verify against developers.doku.com */
  otp?: string;
    /** TODO: verify against developers.doku.com */
  action?: string;
    /** TODO: verify against developers.doku.com */
  originalReferenceNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Verify OTP Binding — POST /direct-debit/core/v1/otp-verification */
export async function briVerifyOtpBinding(
  client: DokuClient, body: BriVerifyOtpBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp-verification", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface BriPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    successPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    paymentType?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function briPayment(
  client: DokuClient, body: BriPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface BriVerifyOtpPaymentBody {
    /** TODO: verify against developers.doku.com */
  otp?: string;
    /** TODO: verify against developers.doku.com */
  action?: string;
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    bankCardToken?: string;
  };
}

/** Verify OTP Payment — POST /direct-debit/core/v1/otp-verification */
export async function briVerifyOtpPayment(
  client: DokuClient, body: BriVerifyOtpPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp-verification", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface BriRefundBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
    /** TODO: verify against developers.doku.com */
  reason?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function briRefund(
  client: DokuClient, body: BriRefundBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface BriCardUnbindingBody {
    /** TODO: verify against developers.doku.com */
  tokenId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Card Unbinding — POST /direct-debit/core/v1/registration-card-unbind */
export async function briCardUnbinding(
  client: DokuClient, body: BriCardUnbindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-card-unbind", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriCardBindingBody {
    /** TODO: verify against developers.doku.com */
  cardData?: string;
    /** TODO: verify against developers.doku.com */
  custIdMerchant?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
    /** TODO: verify against developers.doku.com */
  phoneNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    customerName?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    idCard?: string;
      /** TODO: verify against developers.doku.com */
    country?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    dateOfBirth?: string;
      /** TODO: verify against developers.doku.com */
    successRegistrationUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedRegistrationUrl?: string;
  };
}

/** Card Binding — POST /direct-debit/core/v1/registration-card-bind */
export async function mandiriCardBinding(
  client: DokuClient, body: MandiriCardBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-card-bind", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriRequestOtpBindingBody {
    /** TODO: verify against developers.doku.com */
  otpTrxCode?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Request OTP Binding — POST /direct-debit/core/v1/otp */
export async function mandiriRequestOtpBinding(
  client: DokuClient, body: MandiriRequestOtpBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriVerifyOtpBindingBody {
    /** TODO: verify against developers.doku.com */
  otp?: string;
    /** TODO: verify against developers.doku.com */
  action?: string;
    /** TODO: verify against developers.doku.com */
  originalReferenceNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Verify OTP Binding — POST /direct-debit/core/v1/otp-verification */
export async function mandiriVerifyOtpBinding(
  client: DokuClient, body: MandiriVerifyOtpBindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp-verification", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    successPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    failedPaymentUrl?: string;
      /** TODO: verify against developers.doku.com */
    paymentType?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function mandiriPayment(
  client: DokuClient, body: MandiriPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriRequestOtpPaymentBody {
    /** TODO: verify against developers.doku.com */
  otpTrxCode?: string;
    /** TODO: verify against developers.doku.com */
  journeyId?: string;
    /** TODO: verify against developers.doku.com */
  bankCardToken?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Request OTP Payment — POST /direct-debit/core/v1/otp */
export async function mandiriRequestOtpPayment(
  client: DokuClient, body: MandiriRequestOtpPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriVerifyOtpPaymentBody {
    /** TODO: verify against developers.doku.com */
  otp?: string;
    /** TODO: verify against developers.doku.com */
  action?: string;
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    bankCardToken?: string;
  };
}

/** Verify OTP Payment — POST /direct-debit/core/v1/otp-verification */
export async function mandiriVerifyOtpPayment(
  client: DokuClient, body: MandiriVerifyOtpPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/otp-verification", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriCancelBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  reason?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Cancel — POST /direct-debit/core/v1/debit/cancel */
export async function mandiriCancel(
  client: DokuClient, body: MandiriCancelBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/cancel", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface MandiriCardUnbindingBody {
    /** TODO: verify against developers.doku.com */
  tokenId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Card Unbinding — POST /direct-debit/core/v1/registration-card-unbind */
export async function mandiriCardUnbinding(
  client: DokuClient, body: MandiriCardUnbindingBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-card-unbind", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface DanaPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  urlParam?: Array<unknown>;
    /** TODO: verify against developers.doku.com */
  validUpTo?: string;
    /** TODO: verify against developers.doku.com */
  pointOfInitiation?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    orderTitle?: string;
      /** TODO: verify against developers.doku.com */
    supportDeepLinkCheckoutUrl?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function danaPayment(
  client: DokuClient, body: DanaPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface DanaRefundBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function danaRefund(
  client: DokuClient, body: DanaRefundBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface ShopeepayPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  urlParam?: Array<unknown>;
    /** TODO: verify against developers.doku.com */
  validUpTo?: string;
    /** TODO: verify against developers.doku.com */
  pointOfInitiation?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Payment — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function shopeepayPayment(
  client: DokuClient, body: ShopeepayPaymentBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface ShopeepayRefundBody {
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
    /** TODO: verify against developers.doku.com */
  reason?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function shopeepayRefund(
  client: DokuClient, body: ShopeepayRefundBody, options?: DirectDebitSnapSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}
