/**
 * directDebitLegacy — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface BriRegisterCardCreateTokenBody {
  acquirer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    phone?: string;
      /** TODO: verify against developers.doku.com */
    id_card?: string;
      /** TODO: verify against developers.doku.com */
    country?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    date_of_birth?: string;
  };
  debit_card: {
      /** TODO: verify against developers.doku.com */
    account_email?: string;
      /** TODO: verify against developers.doku.com */
    account_mobile_phone?: string;
      /** TODO: verify against developers.doku.com */
    card_expiry?: string;
      /** TODO: verify against developers.doku.com */
    card_last_four?: string;
  };
}

/** Register Card - Create Token — POST /direct-debit/v1/token */
export async function briRegisterCardCreateToken(
  client: DokuClient, body: BriRegisterCardCreateTokenBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/token", body as unknown as Record<string, unknown>);
}

export interface BriRegisterCardValidateOtpBody {
  debit_card: {
      /** TODO: verify against developers.doku.com */
    token_id?: string;
      /** TODO: verify against developers.doku.com */
    otp?: string;
  };
}

/** Register Card - Validate OTP — POST /direct-debit/v1/token/validate */
export async function briRegisterCardValidateOtp(
  client: DokuClient, body: BriRegisterCardValidateOtpBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/token/validate", body as unknown as Record<string, unknown>);
}

export interface BriRegisterCardResendOtpBody {
  channel: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  acquirer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  debit_card: {
      /** TODO: verify against developers.doku.com */
    token_id?: string;
  };
}

/** Register Card - Resend OTP — POST /direct-debit/v1/token-otp */
export async function briRegisterCardResendOtp(
  client: DokuClient, body: BriRegisterCardResendOtpBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/token-otp", body as unknown as Record<string, unknown>);
}

export interface BriGetCardListBody {
  customer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
  };
}

/** Get Card List — POST /direct-debit/v1/tokens */
export async function briGetCardList(
  client: DokuClient, body: BriGetCardListBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/tokens", body as unknown as Record<string, unknown>);
}

export interface BriPaymentCreatePaymentBody {
  channel: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  acquirer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
  };
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
      /** TODO: verify against developers.doku.com */
    line_items?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    amount?: number;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    token_id?: string;
      /** TODO: verify against developers.doku.com */
    otp_expiration_timestamp?: number;
  };
}

/** Payment - Create Payment — POST /direct-debit/v1/payment */
export async function briPaymentCreatePayment(
  client: DokuClient, body: BriPaymentCreatePaymentBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/payment", body as unknown as Record<string, unknown>);
}

export interface BriPaymentValidateOtpBody {
  channel: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  acquirer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    token?: string;
      /** TODO: verify against developers.doku.com */
    otp?: string;
  };
}

/** Payment - Validate OTP — POST /direct-debit/v1/payment/validate */
export async function briPaymentValidateOtp(
  client: DokuClient, body: BriPaymentValidateOtpBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/payment/validate", body as unknown as Record<string, unknown>);
}

export interface BriPaymentResendOtpBody {
  channel: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  acquirer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    token?: string;
  };
}

/** Payment - Resend OTP — POST /direct-debit/v1/payment-otp */
export async function briPaymentResendOtp(
  client: DokuClient, body: BriPaymentResendOtpBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/payment-otp", body as unknown as Record<string, unknown>);
}

export interface BriPaymentCreateRecurringPaymentBody {
  channel: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  acquirer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
  };
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
      /** TODO: verify against developers.doku.com */
    line_items?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    amount?: number;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    token_id?: string;
      /** TODO: verify against developers.doku.com */
    otp_expiration_timestamp?: number;
  };
}

/** Payment - Create Recurring Payment — POST /direct-debit/v1/payment-recurring */
export async function briPaymentCreateRecurringPayment(
  client: DokuClient, body: BriPaymentCreateRecurringPaymentBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/payment-recurring", body as unknown as Record<string, unknown>);
}

export interface BriDeleteCardBody {
  customer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
  };
  debit_card: {
      /** TODO: verify against developers.doku.com */
    token_id?: string;
  };
}

/** Delete Card — POST /direct-debit/v1/token-delete */
export async function briDeleteCard(
  client: DokuClient, body: BriDeleteCardBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/direct-debit/v1/token-delete", body as unknown as Record<string, unknown>);
}
