/**
 * kki — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface KkiSnapOptions {
  /** CHANNEL-ID header (some flows require e.g. "H2H") */
  channelId?: string;
  /** B2B2C customer token; sent as `Authorization-Customer: Bearer ...` when set */
  customerToken?: string;
}

export interface BindingOnlyBody {
    /** TODO: verify against developers.doku.com */
  accountName?: string;
    /** TODO: verify against developers.doku.com */
  cardData?: string;
    /** TODO: verify against developers.doku.com */
  custIdMerchant?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    customerName?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    dateOfBirth?: string;
  };
}

/** Binding Only — POST /direct-debit/core/v1/registration-card-bind */
export async function bindingOnly(
  client: DokuClient, body: BindingOnlyBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-card-bind", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface PaymentAfpWithBindingBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  chargeToken?: string;
    /** TODO: verify against developers.doku.com */
  otp?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    isBindAndPay?: string;
    customer: {
        /** TODO: verify against developers.doku.com */
      customerId?: string;
        /** TODO: verify against developers.doku.com */
      customerName?: string;
        /** TODO: verify against developers.doku.com */
      postalCode?: number;
    };
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
  };
}

/** Payment AFP with Binding — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function paymentAfpWithBinding(
  client: DokuClient, body: PaymentAfpWithBindingBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface PaymentAfpBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  chargeToken?: string;
    /** TODO: verify against developers.doku.com */
  otp?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
    customer: {
        /** TODO: verify against developers.doku.com */
      customerId?: string;
        /** TODO: verify against developers.doku.com */
      customerName?: string;
        /** TODO: verify against developers.doku.com */
      postalCode?: number;
    };
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
  };
}

/** Payment AFP — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function paymentAfp(
  client: DokuClient, body: PaymentAfpBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface PaymentWithTokenBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  bankCardToken?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    deviceId?: string;
      /** TODO: verify against developers.doku.com */
    originalRequestId?: string;
    account: {
        /** TODO: verify against developers.doku.com */
      accountName?: string;
        /** TODO: verify against developers.doku.com */
      accountNo?: string;
    };
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
  };
}

/** Payment with token — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function paymentWithToken(
  client: DokuClient, body: PaymentWithTokenBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface PaymentWithoutAfpBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  bankCardToken?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
      /** TODO: verify against developers.doku.com */
    lineItems?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    paymentType?: string;
  };
}

/** Payment without AFP — POST /direct-debit/core/v1/debit/payment-host-to-host */
export async function paymentWithoutAfp(
  client: DokuClient, body: PaymentWithoutAfpBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/payment-host-to-host", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface RefundBody {
    /** TODO: verify against developers.doku.com */
  originalReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalExternalId?: string;
    /** TODO: verify against developers.doku.com */
  partnerRefundNo?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  latestTransactionStatus?: string;
    /** TODO: verify against developers.doku.com */
  reason?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Refund — POST /direct-debit/core/v1/debit/refund */
export async function refund(
  client: DokuClient, body: RefundBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/debit/refund", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}

export interface UnbindingBody {
    /** TODO: verify against developers.doku.com */
  tokenId?: string;
  additionalInfo: {
      /** TODO: verify against developers.doku.com */
    channel?: string;
  };
}

/** Unbinding — POST /direct-debit/core/v1/registration-card-unbind */
export async function unbinding(
  client: DokuClient, body: UnbindingBody, options?: KkiSnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/direct-debit/core/v1/registration-card-unbind", {
    body: body as unknown as Record<string, unknown>,
    useSharedKey: true,
    customerToken: options?.customerToken,
    channelId: options?.channelId,
  });
}
