/**
 * o2o — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface AlfaGeneratePaymentCodeBody {
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
      /** TODO: verify against developers.doku.com */
    amount?: number;
  };
  online_to_offline_info: {
      /** TODO: verify against developers.doku.com */
    expired_time?: number;
      /** TODO: verify against developers.doku.com */
    reusable_status?: boolean;
      /** TODO: verify against developers.doku.com */
    info?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    name?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
  };
  alfa_info: {
    receipt: {
        /** TODO: verify against developers.doku.com */
      footer_message?: string;
    };
  };
}

/** Alfa - Generate Payment Code — POST /alfa-online-to-offline/v2/payment-code */
export async function alfaGeneratePaymentCode(
  client: DokuClient, body: AlfaGeneratePaymentCodeBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/alfa-online-to-offline/v2/payment-code", body as unknown as Record<string, unknown>);
}

export interface IndomaretGeneratePaymentCodeCopyBody {
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
      /** TODO: verify against developers.doku.com */
    amount?: number;
  };
  online_to_offline_info: {
      /** TODO: verify against developers.doku.com */
    expired_time?: number;
      /** TODO: verify against developers.doku.com */
    reusable_status?: boolean;
      /** TODO: verify against developers.doku.com */
    info?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    name?: string;
      /** TODO: verify against developers.doku.com */
    email?: string;
  };
  alfa_info: {
    receipt: {
        /** TODO: verify against developers.doku.com */
      footer_message?: string;
    };
  };
}

/** Indomaret - Generate Payment Code Copy — POST /indomaret-online-to-offline/v2/payment-code */
export async function indomaretGeneratePaymentCodeCopy(
  client: DokuClient, body: IndomaretGeneratePaymentCodeCopyBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/indomaret-online-to-offline/v2/payment-code", body as unknown as Record<string, unknown>);
}
