/**
 * paylater — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface GenerateOrderBody {
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
      /** TODO: verify against developers.doku.com */
    line_items?: Array<unknown>;
      /** TODO: verify against developers.doku.com */
    amount?: string;
      /** TODO: verify against developers.doku.com */
    callback_url?: string;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    merchant_unique_reference?: string;
  };
  customer: {
      /** TODO: verify against developers.doku.com */
    id?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
      /** TODO: verify against developers.doku.com */
    phone?: string;
      /** TODO: verify against developers.doku.com */
    address?: string;
      /** TODO: verify against developers.doku.com */
    postcode?: string;
      /** TODO: verify against developers.doku.com */
    state?: string;
      /** TODO: verify against developers.doku.com */
    city?: string;
  };
}

/** Generate Order — POST /akulaku-peer-to-peer/v2/generate-order */
export async function generateOrder(
  client: DokuClient, body: GenerateOrderBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/akulaku-peer-to-peer/v2/generate-order", body as unknown as Record<string, unknown>);
}

export interface CancellationBody {
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    merchant_unique_reference?: string;
      /** TODO: verify against developers.doku.com */
    identifier?: Array<unknown>;
  };
}

/** Cancellation — POST /akulaku-peer-to-peer/v2/cancel */
export async function cancellation(
  client: DokuClient, body: CancellationBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/akulaku-peer-to-peer/v2/cancel", body as unknown as Record<string, unknown>);
}

export interface RefundBody {
  order: {
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
  };
  payment: {
      /** TODO: verify against developers.doku.com */
    merchant_unique_reference?: string;
      /** TODO: verify against developers.doku.com */
    identifier?: Array<unknown>;
  };
  refund: {
      /** TODO: verify against developers.doku.com */
    merchant_unique_reference?: string;
  };
}

/** Refund — POST /akulaku-peer-to-peer/v2/refund */
export async function refund(
  client: DokuClient, body: RefundBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/akulaku-peer-to-peer/v2/refund", body as unknown as Record<string, unknown>);
}
