/**
 * subAccountV1 — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

/** Balance — GET /sac-merchant/v1/balances/${accountId} */
export async function balance(
  client: DokuClient, accountId: string
): Promise<unknown> {
  return client.requestNonSnap("GET", `/sac-merchant/v1/balances/${accountId}`, undefined);
}

export interface TransfersBody {
  transfer: {
      /** TODO: verify against developers.doku.com */
    origin?: string;
      /** TODO: verify against developers.doku.com */
    destination?: string;
      /** TODO: verify against developers.doku.com */
    amount?: number;
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
  };
}

/** Transfers — POST /sac-merchant/v1/transfers */
export async function transfers(
  client: DokuClient, body: TransfersBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/sac-merchant/v1/transfers", body as unknown as Record<string, unknown>);
}

export interface PayoutsBody {
  account: {
      /** TODO: verify against developers.doku.com */
    id?: string;
  };
  payout: {
      /** TODO: verify against developers.doku.com */
    amount?: number;
      /** TODO: verify against developers.doku.com */
    invoice_number?: string;
  };
  beneficiary: {
      /** TODO: verify against developers.doku.com */
    bank_code?: string;
      /** TODO: verify against developers.doku.com */
    bank_account_number?: string;
      /** TODO: verify against developers.doku.com */
    bank_account_name?: string;
  };
}

/** Payouts — POST /sac-merchant/v1/payouts */
export async function payouts(
  client: DokuClient, body: PayoutsBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/sac-merchant/v1/payouts", body as unknown as Record<string, unknown>);
}

export interface CreateSubAccountBody {
  account: {
      /** TODO: verify against developers.doku.com */
    email?: string;
      /** TODO: verify against developers.doku.com */
    type?: string;
      /** TODO: verify against developers.doku.com */
    name?: string;
  };
}

/** Create Sub Account — POST /sac-merchant/v1/accounts */
export async function createSubAccount(
  client: DokuClient, body: CreateSubAccountBody
): Promise<unknown> {
  return client.requestNonSnap("POST", "/sac-merchant/v1/accounts", body as unknown as Record<string, unknown>);
}
