/**
 * subAccountV2 — generated by scripts/generate-products.mjs from the DOKU Postman
 * collection. Re-run `npm run generate` instead of hand-editing.
 *
 * Request field types are inferred from the collection's example bodies (all leaf
 * fields optional). Responses are `unknown` until verified against the docs.
 */
import type { DokuClient } from "../core/client.js";

export interface SubAccountV2SnapOptions {
  /** CHANNEL-ID header (some flows require e.g. "H2H") */
  channelId?: string;
}

export interface BalanceInquiriesBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  profileId?: string;
}

/** Balance Inquiries — POST /sub-account/v2.0/balance-inquiries */
export async function balanceInquiries(
  client: DokuClient, body: BalanceInquiriesBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/balance-inquiries", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface TransactionHistoryBody {
    /** TODO: verify against developers.doku.com */
  accountNo?: string;
    /** TODO: verify against developers.doku.com */
  fromDateTime?: string;
    /** TODO: verify against developers.doku.com */
  toDateTime?: string;
    /** TODO: verify against developers.doku.com */
  pageSize?: string;
    /** TODO: verify against developers.doku.com */
  pageNumber?: string;
}

/** Transaction History — POST /sub-account/v2.0/transaction-history-list */
export async function transactionHistory(
  client: DokuClient, body: TransactionHistoryBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transaction-history-list", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface PurchaseBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  transactionType?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    currency?: string;
      /** TODO: verify against developers.doku.com */
    value?: string;
  };
    /** TODO: verify against developers.doku.com */
  description?: string;
}

/** Purchase — POST /sub-account/v2.0/debit */
export async function purchase(
  client: DokuClient, body: PurchaseBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/debit", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface RefundPurchaseBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  transactionType?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    currency?: string;
      /** TODO: verify against developers.doku.com */
    value?: string;
  };
    /** TODO: verify against developers.doku.com */
  reason?: string;
}

/** Refund Purchase — POST /sub-account/v2.0/debit/cancel */
export async function refundPurchase(
  client: DokuClient, body: RefundPurchaseBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/debit/cancel", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface TransferPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  referenceNo?: string;
    /** TODO: verify against developers.doku.com */
  type?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountNumber?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountName?: string;
}

/** Transfer Payment — POST /sub-account/v2.0/transfer-payment */
export async function transferPayment(
  client: DokuClient, body: TransferPaymentBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transfer-payment", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface TransferInquiryBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  type?: string;
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  remark?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountNumber?: string;
}

/** Transfer Inquiry — POST /sub-account/v2.0/transfer-inquiry */
export async function transferInquiry(
  client: DokuClient, body: TransferInquiryBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transfer-inquiry", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface RegisterSubAccountBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  type?: string;
    /** TODO: verify against developers.doku.com */
  email?: string;
    /** TODO: verify against developers.doku.com */
  name?: string;
    /** TODO: verify against developers.doku.com */
  parentProfileId?: string;
}

/** Register Sub Account — POST /sub-account/v2.0/register */
export async function registerSubAccount(
  client: DokuClient, body: RegisterSubAccountBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/register", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface TransactionStatusBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
}

/** Transaction Status — POST /sub-account/v2.0/transactions-status */
export async function transactionStatus(
  client: DokuClient, body: TransactionStatusBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transactions-status", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

/** Split Rules — POST /sub-account/v2.0/split-rules */
export async function splitRules(
  client: DokuClient, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestNonSnap("POST", "/sub-account/v2.0/split-rules", undefined);
}

export interface PointTopupTransferInquiryBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  type?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  channel?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountNumber?: string;
    /** TODO: verify against developers.doku.com */
  remark?: string;
}

/** Point Topup - Transfer Inquiry — POST /sub-account/v2.0/transfer-inquiry */
export async function pointTopupTransferInquiry(
  client: DokuClient, body: PointTopupTransferInquiryBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transfer-inquiry", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface PointTopupTransferPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  referenceNo?: string;
    /** TODO: verify against developers.doku.com */
  type?: string;
    /** TODO: verify against developers.doku.com */
  channel?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  beneficiaryBankCode?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountNumber?: string;
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountName?: string;
}

/** Point Topup - Transfer Payment — POST /sub-account/v2.0/transfer-payment */
export async function pointTopupTransferPayment(
  client: DokuClient, body: PointTopupTransferPaymentBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transfer-payment", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface VoidTopupBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  transactionType?: string;
  voidAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  reason?: string;
}

/** Void Topup — POST /sub-account/v2.0/topup/void */
export async function voidTopup(
  client: DokuClient, body: VoidTopupBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/topup/void", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface PointPurchaseBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  transactionType?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  description?: string;
}

/** Point Purchase — POST /sub-account/v2.0/debit */
export async function pointPurchase(
  client: DokuClient, body: PointPurchaseBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/debit", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface PointRefundBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalPartnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  originalReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  transactionType?: string;
  refundAmount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  reason?: string;
}

/** Point Refund — POST /sub-account/v2.0/debit/cancel */
export async function pointRefund(
  client: DokuClient, body: PointRefundBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/debit/cancel", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface PointP2pTransferInquiryBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  type?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  channel?: string;
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountNumber?: string;
    /** TODO: verify against developers.doku.com */
  remark?: string;
}

/** Point P2P - Transfer Inquiry — POST /sub-account/v2.0/transfer-inquiry */
export async function pointP2pTransferInquiry(
  client: DokuClient, body: PointP2pTransferInquiryBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transfer-inquiry", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}

export interface PointP2pTransferPaymentBody {
    /** TODO: verify against developers.doku.com */
  partnerReferenceNo?: string;
    /** TODO: verify against developers.doku.com */
  referenceNo?: string;
    /** TODO: verify against developers.doku.com */
  type?: string;
    /** TODO: verify against developers.doku.com */
  channel?: string;
  amount: {
      /** TODO: verify against developers.doku.com */
    value?: string;
      /** TODO: verify against developers.doku.com */
    currency?: string;
  };
    /** TODO: verify against developers.doku.com */
  beneficiaryBankCode?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountNumber?: string;
    /** TODO: verify against developers.doku.com */
  fromAccount?: string;
    /** TODO: verify against developers.doku.com */
  beneficiaryAccountName?: string;
}

/** Point P2P - Transfer Payment — POST /sub-account/v2.0/transfer-payment */
export async function pointP2pTransferPayment(
  client: DokuClient, body: PointP2pTransferPaymentBody, options?: SubAccountV2SnapOptions
): Promise<unknown> {
  return client.requestSnap("POST", "/sub-account/v2.0/transfer-payment", {
    body: body as unknown as Record<string, unknown>,
    channelId: options?.channelId,
  });
}
